name: Deploy test
on:
  push:
    branches:
      - main

jobs:
  git_flows:
    name: Workflows
    runs-on: ubuntu-latest
    env:
      VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      VITE_FIREBASE_MASSAGING_SENDER_ID: ${{ secrets.FIREBASE_MASSAGING_SENDER_ID }}
      VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
    steps:
      - name: first checkout
        uses: actions/checkout@v4

      - name: node installation
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: hello world
        run: echo "hello world"

      - name: npm install
        run: npm install & npm install --global firebase-tools

      - name: auto test
        run: npm run test

      - name: build
        run: npm run build

      - name: firebase deploy
        run: firebase deploy --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
